### ISSUE TITLE
particles cover the whole page, i want it to only cover my hero component but its covering the whole page, im using next js

### ISSUE THREAD

**Issue by Rico-proxy** [tsparticles/react#100]
![issue2](https://github.com/tsparticles/react/assets/56796900/6cec5b67-3a78-4399-a062-4a8595a89293)
![issue1](https://github.com/tsparticles/react/assets/56796900/bb07c418-1c4d-46c9-b8ee-d94b55fa6920)

i want it to only cover the black background image but its stretchin over

this my code below for my hero component
`"use client"
import React from 'react';
import { useCallback } from "react";
import Particles from "react-tsparticles";
//import { loadFull } from "tsparticles"; // if you are going to use `loadFull`, install the "tsparticles" package too.
import { loadSlim } from "tsparticles-slim"; // if you are going to use `loadSlim`, install the "tsparticles-slim" package too.
import Image from 'next/image';

const Hero = () => {
  const particlesInit = useCallback(async engine => {
    console.log(engine);
    // you can initiate the tsParticles instance (engine) here, adding custom shapes or presets
    // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
    // starting from v2 you can add only the features you need reducing the bundle size
    //await loadFull(engine);
    await loadSlim(engine);
}, []);

const particlesLoaded = useCallback(async container => {
    await console.log(container);
}, []);
  return (
    <main>
       <Particles
            id="tsparticles"
            init={particlesInit}
            loaded={particlesLoaded}
            options={{
               fullScreen: {},
                fpsLimit: 120,
                interactivity: {
                    events: {
                        onClick: {
                            enable: true,
                            mode: "push",
                        },
                        onHover: {
                            enable: true,
                            mode: "repulse",
                        },
                        resize: true,
                    },
                    modes: {
                        push: {
                            quantity: 4,
                        },
                        repulse: {
                            distance: 200,
                            duration: 0.4,
                        },
                    },
                },
                particles: {
                    color: {
                        value: "#ffffff",
                    },
                    links: {
                        color: "#ffffff",
                        distance: 150,
                        enable: true,
                        opacity: 0.5,
                        width: 1,
                    },
                    move: {
                        direction: "none",
                        enable: true,
                        outModes: {
                            default: "bounce",
                        },
                        random: false,
                        speed: 6,
                        straight: false,
                    },
                    number: {
                        density: {
                            enable: true,
                            area: 800,
                        },
                        value: 80,
                    },
                    opacity: {
                        value: 0.5,
                    },
                    shape: {
                        type: "circle",
                    },
                    size: {
                        value: { min: 1, max: 5 },
                    },
                },
                detectRetina: true,
                height: 20,
            }}
        />
    <div className="min-h-screen pt-28 flex items-center justify-center ">
 
      <div className=" grid grid-cols-2 gap-5 text-white p-[80px]  items-center">
        <div className="space-y-4">
          <h1 className="text-6xl font-bold">Buy And Sell Digital Currency</h1>
          <p>Bitcoins work just like obtaining any other currency. You can buy and sell them, and that is the future.</p>
          <button className="bg-green-500 hover:bg-white hover:text-black hover:border hover:border-green-500 text-white font-bold py-2 px-4 rounded transition-colors duration-300">
            Our Services
          </button>
        </div>
        <div className="flex justify-center">
          <Image
            src="/assets/hero.png"
            alt="Digital Currency"
            width={500}
            height={300}
            
          />
        </div>
      </div>
    </div>
    </main>
  );
};

export default Hero;
`

and this my page.js
`
import Hero from "@/components/website/Hero";
import HowItWorks from "@/components/website/HowItWorks";

export default function WebPage() {
    return (
      <main className="flex flex-col space-y-5">
    
          <Hero />

          <HowItWorks/>
    </main>
    );
  }`

**Comment by matteobruni** [comment]
https://www.reddit.com/r/tsParticles/comments/w8luvb/why_my_particles_are_full_screen_i_want_them_to/
