### ISSUE TITLE
Deterministic rendering for remotion integration 

### ISSUE THREAD

**Issue by KCFindstr** [tsparticles/react#112]
Hi team,

Thanks for making this wonderful library! I am trying to render some particles in https://www.remotion.dev/. Currently, the main blocker for me is that remotion requires the rendering to be deterministic - it shouldn't rely on the system clock, but a custom hook that provides the current frame number, and all threads should render identical content if providing the same random seed. I am wondering if there is already support for:

1) injecting a custom clock instead of using the system clock
2) setting a random seed that makes the particle system deterministic 

Is it possible to consider this feature request if not available yet?

**Comment by matteobruni** [comment]
There's a function exported by the engine which is:

```
function setRandom(rnd: () => number = Math.random): void
```

You can call the `setRandom` function passing your custom function for randomization. That function will be used everywhere, every random needed uses that. Be careful to return values between 0 and 1, otherwise something may not work as expected.

**Comment by KCFindstr** [comment]
Thanks a lot @matteobruni ! That definitely solved my second question. For the first question, is there a way to pass a custom clock, or manually update the particle system state without playing the animation?

**Comment by matteobruni** [comment]
> Thanks a lot @matteobruni ! That definitely solved my second question. For the first question, is there a way to pass a custom clock, or manually update the particle system state without playing the animation?

No that's not possible, the frames are requested using the `requestAnimationFrame` browser function, you can overwrite that, but you need to pass the timespan since it's used for calculating frames based on the FPS of the browser.

**Comment by KCFindstr** [comment]
I see. Will you consider the feature request to expose the update logic to support custom updates?

**Comment by matteobruni** [comment]
> I see. Will you consider the feature request to expose the update logic to support custom updates?

That could be something doable in the engine, can you open a feature request here? https://github.com/tsparticles/tsparticles

**Comment by KCFindstr** [comment]
Sounds good! Opened https://github.com/tsparticles/tsparticles/issues/5355.
