### ISSUE TITLE
404 for configuration options

### ISSUE THREAD

**Issue by HassanTanveer** [tsparticles/react#30]
The link to particles.json configuration option leads to a 404 error.

This is the link: https://particles.js.org/docs/interfaces/Options_Interfaces_IOptions.IOptions.html

**Comment by matteobruni** [comment]
Sorry, the docs were updated some days ago and there's a new folder structure. The repository is updated, the package will be updated in the new release

**Comment by HassanTanveer** [comment]
Thanks for the quick response!
