### ISSUE TITLE
`console.dir` is left in code

### ISSUE THREAD

**Issue by danhalis** [tsparticles/react#35]
## Issue
I noticed that the library is logging information about `Particles` component to the browser console 
![image](https://github.com/tsparticles/react/assets/60619445/8bb2ca2f-9344-4c35-8d9b-6a2d0a1a8d47)

This is the line that causes the console logging (in `node_modules/react-particles/particles.js`)
![image](https://github.com/tsparticles/react/assets/60619445/412ce490-51f7-4b7a-908b-a21f1f66041c)

These are the packages that I installed:
```
"react-particles": "^2.10.1",
"tsparticles": "^2.10.1",
```
I used the example code from here: https://github.com/tsparticles/react#typescript-support---object

## Attempt to fix
I tried to uninstall and reinstall the package:
```
 npm uninstall react-particles
 npm install react-particles
```
but that line of code still remains in the downloaded code in `node_modules`.

**Comment by matteobruni** [comment]
It's a known issue (ref https://github.com/matteobruni/tsparticles/issues/5003) and it will be fixed soon, Lerna update to v7 had some issues and I couldn't build the project

**Comment by matteobruni** [comment]
Published update with the fix
