### ISSUE TITLE
Vector.js error

### ISSUE THREAD

**Issue by fakhrul10** [tsparticles/react#83]
I'm having an error at @tsparticles/engine/browser/Core/Utils/Vector.js
Uncaught TypeError: Class extends value undefined is not a constructor or null

![tsCapture](https://github.com/tsparticles/react/assets/1200339/c629b8a2-b017-4ced-9fa2-f01bedcf787d)

Any resolution for this?

**Comment by matteobruni** [comment]
https://github.com/tsparticles/vue3/issues/57 here's a workaround
