### ISSUE TITLE
Next JS

### ISSUE THREAD

**Issue by desduvauchelle** [tsparticles/react#85]
Thanks for the work!

Doesn't work in Next JS. Any chance you have some docs/examples of usages in Next JS? 

I tried to do a dynamic import but then I don't have access to initParticlesEngine, when I try to do a dynamic import of that, it says it's a hook that cannot be used inside a useEffect. 

Any help appreciated.

**Comment by matteobruni** [comment]
There are two samples using Next.js here: https://github.com/tsparticles/react/tree/main/apps

Be aware that currently there's a known issue: https://github.com/tsparticles/react/issues/83
