### ISSUE TITLE
After these changes it seems not working with autoPlay: false

### ISSUE THREAD

**Issue by Squikle** [tsparticles/react#99]
@Kritika30032002

Looks like something important was removed with that bunch of deleted code. When I use the new function version of the Particles component I end up with the destroyed variable as 'true' even before calling play().
Duration isn't set in options and by call stack, it happens some safelyCallDestroy() where it calls destroy() itself

With those concerns, I've decided to try the original class version and it works perfectly fine without changing any of my code
I also created 2 branches in case of need to reproduce the problem. Please, see https://github.com/Squikle/MemIt/branches
-npm run dev
-go to http://localhost:5173/terms/1
-press the green button to finish a stack
-see particles don't start with the new function component version and some logs of the destroyed variable show it's 'true'

Sorry I don't have much time for deep investigation or fork but contact me if you need some additional information

**Comment by Kritika30032002** [comment]
Can you brief what you expect from me to do?

**Comment by matteobruni** [comment]
> @Kritika30032002
> 
> Looks like something important was removed with that bunch of deleted code. When I use the new function version of the Particles component I end up with the destroyed variable as 'true' even before calling play(). Duration isn't set in options and by call stack, it happens some safelyCallDestroy() where it calls destroy() itself
> 
> With those concerns, I've decided to try the original class version and it works perfectly fine without changing any of my code I also created 2 branches in case of need to reproduce the problem. Please, see https://github.com/Squikle/MemIt/branches -npm run dev -go to http://localhost:5173/terms/1 -press the green button to finish a stack -see particles don't start with the new function component version and some logs of the destroyed variable show it's 'true'
> 
> Sorry I don't have much time for deep investigation or fork but contact me if you need some additional information

I've seen your repo and you changes some private variables. That would create some unexpected behaviors, and the destroy could be one of them.

I've tried to create a similar effect (I've not run your repo, but I think it's very close to what you are achieving) here:

https://codesandbox.io/p/sandbox/hopeful-sound-d3qq8j?file=%2Fsrc%2FApp.js%3A33%2C21

The `container.addEmitter` in JavaScript is not a problem, in TypeScript you need to import the `EmitterContainer` and cast the container to that type from `@tsparticles/plugin-emitters`. The `container.addEmitter` returns the `EmitterInstance` class, that you can pause/stop manually. In the sample created the Emitters have a life options, to stop both emitters after a second.

**Comment by Squikle** [comment]
uh, I'll check this one. Thank you a lot for your time
